###Parameters
GET http://localhost:5000/api/GetParameters HTTP/1.1

### Optimalisation
POST http://localhost:5000/api/Optimalisation HTTP/1.1
Content-Type: application/json

< ./parameters.json

### Best team based on optimalisation
POST http://localhost:5000/api/KnapsackTeamBasedOnOptimalisation/10 HTTP/1.1
Content-Type: application/json

< ./parameters.json


### ReplaceInMyTeam
### Backpackers 2391262
### Ks Kelpie 833896
### AdrianTeam 2692525
@teamId = 2391262 
@numberOfPlayersToReplace = 1

POST http://localhost:5000/api/ReplaceInMyTeam/{{teamId}}/{{numberOfPlayersToReplace}} HTTP/1.1
Content-Type: application/json

< ./parameters.json


### Best team based on optimalisation
POST http://localhost:5000/api/KnapsackTeamBasedOnOptimalisation/10 HTTP/1.1
Content-Type: application/json

< ./parameters.json

### PickTeam
POST http://localhost:5000/api/PickTeam/{{teamId}} HTTP/1.1
Content-Type: application/json

< ./parameters.json
